# 使用官方的 Node.js 20 映像作為基礎映像
FROM node:20

# 設定容器內的工作目錄，WORKDIR 是 Dockerfile 的指令，用來設置在容器內部用於存儲應用程式檔案的目錄。
WORKDIR /usr/src/app

# 將 package.json 和 package-lock.json 複製到工作目錄
COPY package*.json ./

# 安裝專案依賴
RUN npm install

# 將其餘的應用程式代碼複製到工作目錄
COPY . .

# 開放應用程式運行的端口
EXPOSE 3000

# 運行應用程式的命令
CMD ["npm", "start"]